config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  resources :pins
  get 'welcome/index'

root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
get 'mypins' => 'pins#mypins'
  get 'pinsof/:user_id' => 'pins#pinsof', :as => "pinsof"
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pin.rb
class Pin < ApplicationRecord
  validates :photo, presence:true
  validates :description, presence:true

  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception


end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :set_pin, only: [:show, :edit, :update, :destroy]
  after_action :authenticate_user!, except:[ :show, :index ]


def pinsof
  @user_id = params[:user_id]
  @user = User.find(@user_id)
  @pins = @user.pins

end

def mypins
  @pins = current_user.pins
end
  # GET /pins
  # GET /pins.json
  def index
    @pins = Pin.all
  end

  # GET /pins/1
  # GET /pins/1.json
  def show
    @pins = current_user.pins
  end

  # GET /pins/new
  def new
    @pins = current_user.pins
    @pin = Pin.new
  end

  # GET /pins/1/edit
  def edit
  end

  # POST /pins
  # POST /pins.json
  def create
    @pin = Pin.new(pin_params)
    @pin.user_id = current_user.id

    respond_to do |format|
      if @pin.save
        format.html { redirect_to @pin, notice: 'Pin was successfully created.' }
        format.json { render :show, status: :created, location: @pin }
      else
        format.html { render :new }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pins/1
  # PATCH/PUT /pins/1.json
  def update
    respond_to do |format|
      if @pin.update(pin_params)
        format.html { redirect_to @pin, notice: 'Pin was successfully updated.' }
        format.json { render :show, status: :ok, location: @pin }
      else
        format.html { render :edit }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pins/1
  # DELETE /pins/1.json
  def destroy
    @pin.destroy
    respond_to do |format|
      format.html { redirect_to pins_url, notice: 'Pin was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pin
      @pin = Pin.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pin_params
      params.require(:pin).permit(:photo, :description, :name)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

    <title >Mi Pinterest</title>
    <%= csrf_meta_tags %>

    <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <%= stylesheet_link_tag    '/assets/application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag '/assets/application', 'data-turbolinks-track': 'reload' %>

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

    <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/masonry/4.2.0/masonry.pkgd.js"></script>


  </head>

  <body>
  <%= render 'shared/navbar'%>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/pins/_form.html.erb
<%= form_with(model: pin, local: true) do |form| %>
  <% if pin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pin.errors.count, "error") %> prohibited this pin from being saved:</h2>

      <ul>
      <% pin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="form-group">
  <div class="field">
    <%= form.label "Fotografia" %>
    <%= form.text_field :photo, id: :pin_photo, :class=>"form-control", :placeholder=>"Link" %>
  </div>
</div>
<div class="form-group">
  <div class="field">
    <%= form.label "Nombre" %>
    <%= form.text_field :name, id: :pin_name, :class=>"form-control", :placeholder=>"Nombre" %>
  </div>
</div>
<div class="form-group">
  <div class="field">
    <%= form.label "Descripcion" %>
    <%= form.text_field :description, id: :pin_description, :class=>"form-control", :placeholder=>"Descripcion", :rows=>"10", :cols=>"30"%>
  </div>
</div>
    <div class="form-group">
      <div class="field">
        <% @pins.each do |pin|%>
        <%= form.hidden_field_tag :@user_id, pin.user.id %>
            <% end %>
      </div>
    </div>
  <div class="actions">
    <%= form.submit "Crear", :class=>"btn"%>
  </div>

<% end %>

app/views/pins/edit.html.erb
<div class="container">
<h1>Editing Pin</h1>
<div class="col-md-6">
<%= render 'form', pin: @pin %>

<%= link_to 'Show', @pin %> |
<%= link_to 'Back', pins_path, :class=>"btn" %>
</div>
</div>

app/views/pins/index.html.erb
<p id="notice"><%= notice %></p>


<div class="grid">
  <h1>Pins</h1>

<% @pins.each do |pin| %>
<div class="grid-item" style="...">
  <div class="thumbnail">

    <%= pin.name%>
<%= image_tag(pin.photo, :class=>'img-responsive') %>
<%= pin.description %>
<div class="buttons" style="margin-top:10px; margin-bottom:10px">

  <% if current_user.nil? %>
      <%= link_to 'Show', (pin), :class =>'btn' %>
      <% else %>
      <%= link_to 'Show', (pin), :class =>'btn' %>
      <% end %>
</div>
</div>
</div>

    <% end %>

<br>
<% if user_signed_in? %>
<%= link_to 'New Pin', new_pin_path, :class =>'btn' %>
<% end %>


</div>
<script type="text/javascript">
    var elem = document.querySelector('.grid');
    var msnry = new Masonry(elem,{
        itemSelector: '.grid-item',
        columnWidth: 200
    });
  $(window).load(function(){
      var elem = document.querySelector ('.grid');
      var msnry = new Masonry(elem,{
          itemSelector: '.grid-item',
          columnWidth: 200
      });
  })

</script>

app/views/pins/mypins.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
  <h1>Mis Pins</h1>


  <% @pins.each do |pin| %>
      <div class="col-md-3">
        <div class="thumbnail">
          <%= pin.name%>
          <%= image_tag(pin.photo, :class=>'img-responsive') %>
          <%= pin.description %>

          <div class="buttons" style="margin-top:10px; margin-bottom:10px">
            <%= link_to 'Show', (pin), :class =>'btn' %>
            <%= link_to 'Edit', edit_pin_path(pin), :class=>'btn' %>
            <% if user_signed_in? %>
                <%= link_to 'Destroy', pin, :class=>'btn', method: :delete, data: { confirm: 'Are you sure?' }, :class=>'btn' %>
            <% end %>
          </div>
        </div>
      </div>
  <% end %>

  <br>
  <% if user_signed_in? %>
      <%= link_to 'New Pin', new_pin_path, :class =>'btn' %>
  <% end %>
</div>

app/views/pins/new.html.erb
<div class="container">
<h1>Agregar Nuevo pin</h1>

<div class="col-md-6">
<%= render 'form', pin: @pin , pins: @pins, :class=>"btn"%>

<%= link_to 'Back', pins_path , :class=>"btn"%>
</div>
</div>

app/views/pins/pinsof.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
  <h1>Mis Pins</h1>


  <% @pins.each do |pin| %>
      <div class="col-md-3">
        <div class="thumbnail">
          <%= pin.name%>
          <%= image_tag(pin.photo, :class=>'img-responsive') %>
          <%= pin.description %>

          <div class="buttons" style="margin-top:10px; margin-bottom:10px">
            <%= link_to 'Show', (pin), :class =>'btn' %>
            <%= link_to 'Edit', edit_pin_path(pin), :class=>'btn' %>
            <% if user_signed_in? %>
                <%= link_to 'Destroy', pin, :class=>'btn', method: :delete, data: { confirm: 'Are you sure?' }, :class=>'btn' %>
            <% end %>
          </div>
        </div>
      </div>
  <% end %>

  <br>
  <% if user_signed_in? %>
      <%= link_to 'New Pin', new_pin_path, :class =>'btn' %>
  <% end %>
</div>

app/views/pins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @pin.name %>
</p>
<p>
  <strong>Fotografia:</strong>
  <%= image_tag(@pin.photo, :style => 'width:500px') %>
</p>

<p>
  <strong>Descripcion:</strong>
  <%= @pin.description %>
</p>

<%= link_to 'Edit', edit_pin_path(@pin) %> |
<%= link_to 'Back', pins_path %>

<%= link_to "Mas pins del mismo usuario", pinsof_path(@pin.user.id) %>

app/views/shared/_navbar.html.erb

<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= root_path %>">My Pinterest</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="<%= pins_path %>">Pins<span class="sr-only">(current)</span></a></li>



      </ul>

      <ul class="nav navbar-nav navbar-right">
        <% if current_user.nil? %>
        <li><a href="<%= new_user_session_path %>">Ingreso</a></li>
        <li><a href="<%= new_user_registration_path %>">Registro</a></li>
        <%else%>
            <li><a href="<%= mypins_path %>">Mis pins</a></li>
        <li><a href="<%= destroy_user_session_path %> " data-method="delete">Salir</a></li>
        <%end%>

      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/welcome/index.html.erb
<div class="container">
<div class="jumbotron">
  <h1>Bienvenido</h1>
  <p>Luz Lorena Alvarez Trejo</p>
  <p><a href="https://es.wikipedia.org/wiki/Pinterest" type="button" class="btn btn-default glyphicon glyphicon-record " >Informacion</a></p>
</div>
</div>

<div class="container">
<div class="row">
  <div class="col-md-4">
    <h2 style="color:gainsboro" >HARRY POTTER</h2>
<p style="color:gainsboro" >Harry Potter (también abreviado HP) es una serie de novelas fantásticas escrita por la autora británica J. K. Rowling,
  considerada una de las sagas más importantes de la historia. Realmente la más leída según el Libro de los récords Guiness.
  En ella se describen las aventuras del joven aprendiz de magia y hechicería Harry Potter y sus amigos Hermione Granger y Ron Weasley,
  durante los años que pasan en el Colegio Hogwarts de Magia y Hechicería. El argumento se centra en la lucha entre Harry Potter y el malvado
  mago Lord Voldemort, quien asesinó a los padres de Harry en un intento fallido de matar a Harry, para así poder acabar con la profecía
  que citaba su propia muerte. Voldemort no logra acabar con la vida de Harry Potter, pues este último, al estar protegido por el amor
  de su madre, logra protegerse, y a la vez, adquirir una relación (hablando tanto de manera mental como de poderes) con Voldemort.
  De ahí viene su cicatriz con forma de rayo (JK Rowling explicó que la forma de esta cicatriz era tan solo por su gusto a los rayos, no
  tenía nada escondido detrás)</p>
</div>

  <div class="col-md-4">
    <h2 style="color:gainsboro" >PRIMER LIBRO</h2>
<p style="color:gainsboro" >Harry Potter y la piedra filosofal (Harry Potter and the Philosopher's Stone) es el
  primer libro de la serie, fue publicado en Reino Unido el 30 de junio de 1997 y en español en marzo de 1999.
  12 Se trata de uno de los libros más vendidos de la historia, las estimaciones de sus ventas mundiales superan
  los 110 millones de copias. En la primavera de 2007, una primera edición firmada por Rowling fue subastada en Londres por £27 876.13

  En esta primera obra se introducen la mayoría de los personajes principales de la serie, así como muchos de los lugares
  donde se desarrollará la acción. Se narran los primeros pasos de Harry en el mundo de la magia, así como su primer enfrentamiento
  con Voldemort, quien en su búsqueda de la inmortalidad quiere obtener el poder de la piedra filosofal.</p>
  </div>

      <div class="col-md-4">
        <h2 style="color:gainsboro" >IMPACTO A LA SOCIEDAD</h2>
<p style="color:gainsboro" >El incremento del hábito de la lectura entre los niños y jóvenes ha sido la tendencia más destacada que se le atribuyó a Harry Potter.
  Una encuesta llevada a cabo en 2006 por Kids and Family Reading Report y Scholastic arrojó como resultados que el 51 % de los lectores de la
  serie de entre 5 y 17 años dijo que no había leído por placer anteriormente a Harry Potter, pero que después sí lo hace. Además, el estudio afirma
  que el 65 % de los niños y el 76 % de los padres declaraba que el desempeño escolar de ellos mismos o de sus hijos había mejorado desde que
  empezaron a leer los libros.52 Charlie Griffiths, director de la National Literacy Association, dijo «cualquiera que persuada a los niños a leer
  debería ser atesorado, y lo que Rowling nos ha dado con Harry Potter es por poco un milagro».53 Por su parte, el Primer Ministro británico, Gordon
  Brown, alabó a la escritora diciendo: «Creo que J. K. Rowling ha hecho más por la literatura que ningún otro ser humano».54</p>
      </div>
    </div>
<img src="https://vignette3.wikia.nocookie.net/harrypotter/images/9/9d/Harry-Potter-Wizarding-World-Weekly.jpg/revision/latest/scale-to-width-down/670?cb=20160914202759" style="width:500px"
class="img-responsive">
</div>